jobs:
  include:
    - stage: test
      language: java
      dist: xenial
      sudo: false
      script:
        - ./gradlew test
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/

    - stage: build
      language: minimal
      env:
       - REPO=ankjevel/subscriber
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t $REPO:latest .
        - docker push $REPO:latest

    - stage: build_and_deploy_tag
      language: minimal
      env:
      - REPO=ankjevel/subscriber
      - NAMESPACE="subscriber"
      - DEPLOYMENT="listener"
      - CONTAINER="listener"
      - DEPLOY_SCRIPT="https://gist.githubusercontent.com/ankjevel/fc444cdb248287a97242ced271ece388/raw/69f469562ebe46ef15e066fc574d5d865a5e83ee/deploy.sh"
      script:
        - export TAG="${TRAVIS_TAG/v/}"
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t $REPO:latest-tag-release .
        - docker tag $REPO:latest-tag-release $REPO:$TAG
        - docker push $REPO:latest-tag-release
        - docker push $REPO:$TAG
        - source <(curl "$DEPLOY_SCRIPT" -s 2>&1)

stages:
  - name: test
  - name: build
    if: branch = master AND type != pull_request AND tag !~ /^v/
  - name: build_and_deploy_tag
    if: tag =~ /^v/

notifications:
  email: false
