version: '3.7'

services:
  redis:
    image: redis:4.0-alpine
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    networks:
      - service

networks:
  service:
